version: "3.8"

services:
  mongo-db:
    image: mongo:4.0.3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-user
      - MONGO_INITDB_ROOT_PASSWORD=sasa1234
    volumes:
      - ./mongo:/data/mongo
    ports:
      - 27017:27017